### PR TITLE
Have linz-bde-uploader-schema-load cleanly exit on error

### LINKED ISSUE #159: Schema loader returns success in presence of errors
Example:
```
$ linz-bde-uploader-schema-load test
Loading DBE uploader schema in database test (extension mode on)
ERROR:  table "revision" is not a member of the extension being created
ERROR:  table "applied_patches" is not a member of the extension being created
Loading /usr/share/linz-bde-uploader/sql//01-bde_control_tables.sql
Loading /usr/share/linz-bde-uploader/sql//02-bde_control_functions.sql
Loading /usr/share/linz-bde-uploader/sql//03-bde_control_version.sql
Loading /usr/share/linz-bde-uploader/sql//99-patches.sql
$ echo $?
0
```

You can see ERROR lines, but the exit code is still 0

### PR DESCRIPTION
**Pull request by strk**
Closes #159

### CODE REVIEW

File: bin/linz-bde-uploader-schema-load.pl [hunk 1]
```diff
@@ -66,9 +66,12 @@ sub help
 
 if ( ${EXTENSION_MODE} )
 {
-    `$PSQL -c 'CREATE EXTENSION IF NOT EXISTS table_version;'` || die;
```
Comment (palmerj) [inline bin/linz-bde-uploader-schema-load.pl]: Thanks best option is to provide argument to die. General syntax is:

some_condition || die "message";

Comment (strk) [reply bin/linz-bde-uploader-schema-load.pl]: Added messages with a02f768
